Repository ergochat/ergo, pull requests merged in 2020-09, with the labels that each got.

#1250 changelog for v2.3.0
  CHANGELOG.md
Labels: release blocker

#1249 PONG param 0 should be server name
  irc/handlers.go
Labels: release blocker

#1120 Initial RELAYMSG implementation
  conventional.yaml
  default.yaml
  gencapdefs.py
  irc/caps/defs.go
  irc/client_lookup_set.go
  irc/commands.go
  irc/config.go
  irc/handlers.go
  irc/help.go
  irc/roleplay.go
  irc/server.go
  irc/strings.go
Labels: release blocker

#1269 fix websocket listeners with proxy-before-TLS closing on bad PROXY lines
  irc/utils/proxy.go
Labels: bug

#1271 fix #1240
  irc/config.go
  irc/handlers.go
  irc/roleplay.go
Labels: compatibility-break

#1278 fix channel history recorded for SANICK
  irc/nickname.go
Labels: bug

#1286 fix #1284
  irc/getters.go
  irc/nickserv.go
  irc/server.go
  irc/utils/net.go
Labels: compatibility-break
