Repository ergochat/ergo, pull requests merged in 2022-05, with the labels that each got.

#1947 MANUAL.md: clarify appropiate privs for invite
  docs/MANUAL.md
Labels: documentation

#1961 fix critical bugs in draft/read-marker
  irc/accounts.go
  irc/client.go
  irc/getters.go
  irc/handlers.go
Labels: bug, release blocker

#1962 only send MARKREAD to sessions with the read-marker cap
  irc/handlers.go
Labels: bug
