Repository ergochat/ergo, pull requests merged in 2023-09, with the labels that each got.

#2088 fix #1997
  default.yaml
  irc/email/email.go
  traditional.yaml
Labels: compatibility-break

#2089 upgrade go-ident
  go.mod
  go.sum
  vendor/github.com/ergochat/go-ident/client.go
  vendor/modules.txt
Labels: bug

#2090 changelog for v2.12.0-rc1
  CHANGELOG.md
Labels: documentation

#2092 Fix typo in ACCOUNT_NAME_MUST_BE_NICK code
  irc/handlers.go
Labels: bug
